language: python
sudo: false # use container based infrastructure
env:
    global:
        - TESTMODEL_URL=http://localhost:8080/intermine-demo
        - TESTMODEL_PATH=intermine-demo
before_install:
    - ./config/travis/init.sh
script: 
    - python setup.py test livetest
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
    - "pypy"
    - "pypy3"
